image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.12

sources:
  - service
  - ingress

provider: aws

# Required IAM Permissions
# https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md#iam-permissions

aws:
  accessKey: XXXXXXXXXXXXXXXXX # to change
  secretKey: XXXXXXXXXXXXXXXXX # to change
  region: eu-west-2 # to change
  zoneType: public

domainFilters:
  - example.com # to change

registry: txt
txtOwnerId: example # to change
policy: sync

rbac:
  create: true
  create: true
  apiVersion: v1
